### ISSUE TITLE
Monitor FrontEnd UI performance during WDIO test.

### ISSUE THREAD

**Issue by ShettyAkarsh** [cerner/terra-toolkit-boneyard#45]
This request is to implement the Monitoring of Frontend UI Performance using Lighthouse API's while running the WDIO tests. this should cover the following items.

1.  Provide overall performance score for the particular test case.
2. Compare the previous and current test performance score and check if there is any increase in performance.
3. Provide the consolidated report for performance.

## @ Mentions
@ryanthemanuel

**Comment by emilyrohrbough** [comment]
We investigated this a while back on this issue: https://github.com/cerner/terra-toolkit/issues/129
Just wanted to close the loop 😄

**Comment by supreethmr** [comment]
As part of investigation we have chosen [lighthouse node module API](https://github.com/GoogleChrome/lighthouse/blob/master/docs/readme.md#using-programmatically) for monitoring performance score for front end. 

LightHouse Node module enables us to capture performance metrics for an component by running `lighthouse(componentUrlToTest, lightHouseOptions)` method. Lighthouse validates a component on various aspects of web-app like performance, progress-web-app, best-practices, accessibility and SEO. With our current implementation we are trying to validate only performance score of an page / component.

Following are the 6 metrics which contributes to Lighthouse performance score for a page :
1. [First Contentful Paint](https://web.dev/first-contentful-paint/?utm_source=lighthouse&utm_medium=devtools): marks the time at which the first text or image is painted.

2. [First Meaningful Paint](https://web.dev/first-meaningful-paint/?utm_source=lighthouse&utm_medium=devtools): measures when the primary content of a page is visible.

3. [Speed Index](https://web.dev/speed-index/?utm_source=lighthouse&utm_medium=devtools):shows how quickly the contents of a page are visibly populated.

4. [First CPU Idle](https://web.dev/first-cpu-idle/?utm_source=lighthouse&utm_medium=devtools): marks the first time at which the page's main thread is quiet enough to handle input.

5. [Time to interactive](https://web.dev/interactive/?utm_source=lighthouse&utm_medium=devtools): is the amount of time it takes for the page to become fully.

6. [Maximum potential First Input Delay](https://web.dev/fid/?utm_medium=devtools&utm_source=lighthouse): that your users could experience is the duration, in milliseconds, of the longest.

Lighthouse provides html report as result object which provides detailed insight of page performance as shown below : 

<img width="1113" alt="Screen Shot 2020-07-20 at 7 43 40 PM" src="https://user-images.githubusercontent.com/12869809/87947754-66c66b80-cac1-11ea-8e3b-8cae340399e3.png">

**Implementation Details :** 

- we are calling `lighthouse()` method from `afterTest` hook to capture performance for each page that has WDIO test written for it.

- Saving reports generated by lighthouse for each test under reports -> html folder.

- Lighthouse has only two modes (Mobile, Desktop) of device to test page performance. hence generating report for all the viewports would require more memory. Viewports are classified into two types for lighthouse testing respectively [tiny, small] -> Mobile and [medium, large, huge, enormous] -> Desktop. This will restrict report generation of page for each provided viewports instead reports are generated on classified viewports [mobile, desktop].

- In addition to these we do also restrict report generation for test if there is no difference between previous report and current report or if the difference between both reports score is greater than allowed miss-match range. ( Since reports will have some variance when ran multiple times )

- Consolidate report is generated with name `performance-report.html` containing details of lighthouse report that is generated for each page in test suite.

- Consolidate report provides easy access to light house reports on click of the performance-score.

- Comparison happens between saved reports and newly generated reports in `afterTest` hook. existing performance score and new performance score will be displayed on consolidated report for reference. but previous reports will be always re-written if the new report is generated for same test. (to reduce the memory consumption)

<img width="1667" alt="Screen Shot 2020-07-20 at 9 40 07 PM" src="https://user-images.githubusercontent.com/12869809/87960643-3935ee00-cad2-11ea-9c39-91f8b9002bd0.png">

**Additional Required Features :** 
- Should provide options to enable and disable lighthouse run so that it can be skipped whenever we need to run only wdio tests for page. consumer should also be able to set average performance score for tests to pass performance test. ( Tried adding it as process.env variables in [wdio.config.js](https://github.com/cerner/terra-toolkit-boneyard/blob/10c52638e227947453da0b267f3f68a61b885efb/config/wdio/wdio.conf.js#L55-L58) and [wdio.runner-cli](https://github.com/cerner/terra-toolkit-boneyard/blob/10c52638e227947453da0b267f3f68a61b885efb/scripts/wdio/wdio-runner-cli.js#L27-L28)

- Should Integrate Lighthouse with Jenkins and Travis CI ( Lighthouse V6 requires node version to be greater than or equal to 10 )

- Should integrate output of traces to lighthouse report which provides detailed insights with dev-tools time-logging.

Reference for Lighthouse Integration with CLI : https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#configuration

Reference for Lighthouse : https://github.com/GoogleChrome/lighthouse/blob/44d055142f443d0ecaf3fa24c0b8aa9f1f0d98d5/readme.md#lighthouse-integrations-in-web-perf-services

Link to Light-house Implementation Branch : https://github.com/cerner/terra-toolkit-boneyard/tree/lighthouse-Integration.

**Comment by emilyrohrbough** [comment]
Will we be able to use the wdio lighthouse tools when we go to webdriver.io v6? 
https://webdriver.io/docs/devtools-service.html#performance-testing

**Comment by supreethmr** [comment]
we could use but wdio lighthouse tools lacks ( html report as shown in above screenshot )reporting ability like lighthouse node module.

**Comment by yuderekyu** [comment]
hey i took a peak at the branch and have some questions

1. why not make lighthouse a service? right now, we set the base wdio config's hooks to execute lighthouse logic. we could achieve the same goal by extracting that into its own service and avoid polluting the config; we'd get separation of concerns and modularity yay!
2. we use `chrome-launcher` to launch chrome in the after command. is it possible to hit the existing chrome driver ran for wdio tests instead?

**Comment by supreethmr** [comment]
> why not make lighthouse a service? right now, we set the base wdio config's hooks to execute lighthouse logic. we could achieve the same goal by extracting that into its own service and avoid polluting the config; we'd get separation of concerns and modularity yay!

The main reason for adding lighthouse logic to wdio config hook `afterTest` was to get easy access to global objects like test page urls to run lighthouse performance test and since `afterTest` hook does run for each test It removed the need of configuring the lighthouse to run on each test( like wdio ).

> we use chrome-launcher to launch chrome in the after command. is it possible to hit the existing chrome driver ran for wdio tests instead?
Good suggestion, haven't tried before, I will check if we can access chrome driver launched for wdio in wdioConfig hooks and I think this might need some additional check to be added to handle if user runs wdio only on specific browsers other than chrome. ( Since Lighthouse node api runs only on chrome )

> should this be an opt-in or opt-out feature?
yes user can disable the run with cli argument `--runLightHouse=false / true` through tt-wdio command.

**Comment by yuderekyu** [comment]
> > why not make lighthouse a service? right now, we set the base wdio config's hooks to execute lighthouse logic. we could achieve the same goal by extracting that into its own service and avoid polluting the config; we'd get separation of concerns and modularity yay!
> 
> The main reason for adding lighthouse logic to wdio config hook `afterTest` was to get easy access to global objects like test page urls to run lighthouse performance test and since `afterTest` hook does run for each test It removed the need of configuring the lighthouse to run on each test( like wdio ).
> 

wdio services have access to the same wdio hooks available in the config, which includes the `afterTest` hook. in my mind, we can move lighthouse logic to a service, then use the service in the wdio config. http://v4.webdriver.io/guide/testrunner/services.html

**Comment by supreethmr** [comment]
> > > why not make lighthouse a service? right now, we set the base wdio config's hooks to execute lighthouse logic. we could achieve the same goal by extracting that into its own service and avoid polluting the config; we'd get separation of concerns and modularity yay!
> > 
> > 
> > The main reason for adding lighthouse logic to wdio config hook `afterTest` was to get easy access to global objects like test page urls to run lighthouse performance test and since `afterTest` hook does run for each test It removed the need of configuring the lighthouse to run on each test( like wdio ).
> 
> wdio services have access to the same wdio hooks available in the config, which includes the `afterTest` hook. in my mind, we can move lighthouse logic to a service, then use the service in the wdio config. http://v4.webdriver.io/guide/testrunner/services.html

Thank you for the reference..! I have updated branch with custom service.

**Comment by supreethmr** [comment]
Lighthouse CI : https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md
- I tried integrating Lighthouse CI Module to Travis since existing Lighthouse node module had a limitation of not able to access report folder as specified above.
- Lighthouse CI requires [lighthouse-ci-server](https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/getting-started.md#the-lighthouse-ci-server) to store the generated lighthouse reports. 
- Lighthouse CI is limited only for CI environments and user would not be able to run performance tests locally with LHCI.
- Lighthouse CI require custom server to get the urls of page to be tested / to run the site for testing performance of individual page.
- Since user will not able to test the performance score in local machine it would be hard to test the changes that were made to improve the performance.
- Reports generated by LHCI will vary from the report generated by LH node module making them difficult to compare.
- Hence instead of having both LHCI for CI and LH node module for local testing. Making changes in LH node module to make CI compatible seems to feasible.

Need suggestions on integrating LightHouse with CI ( Jenkins, Travis ) :

- The current implementation of lighthouse in toolkit does runs on Travis. But since we don't have access to travis build folders. the consolidate report created while travis build will be inaccessible. 
- Adding lighthouse reports under jenkins artifacts directory will enable consumers to view and compare report generated by jenkins build and the report generated on local machine. ( Not sure whether we can add / archive a lighthouse report folder to Jenkins artifacts directory ) like wdio screenshots.
Tried testing current code changes in Jenkins for strengthJS project it throws below error. ( Might need chrome launcher to be installed on docker machine before calling lighthouse. )

```
․Error: 
    at new LauncherError (/app/node_modules/chrome-launcher/src/utils.ts:31:18)
    at new ChromePathNotSetError (/app/node_modules/chrome-launcher/dist/utils.js:44:9)
    at Object.linux (/app/node_modules/chrome-launcher/src/chrome-finder.ts:153:11)
    at Function.getFirstInstallation (/app/node_modules/chrome-launcher/src/chrome-launcher.ts:183:61)
    at Launcher.<anonymous> (/app/node_modules/chrome-launcher/src/chrome-launcher.ts:229:37)
    at Generator.next (<anonymous>)
    at /app/node_modules/chrome-launcher/dist/chrome-launcher.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:9:12)
    at Launcher.launch (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:156:16)
    at Object.<anonymous> (/app/node_modules/chrome-launcher/src/chrome-launcher.ts:75:18)
    at Generator.next (<anonymous>)
    at /app/node_modules/chrome-launcher/dist/chrome-launcher.js:13:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:9:12)
    at Object.launch (/app/node_modules/chrome-launcher/dist/chrome-launcher.js:40:12)
```

**Comment by supreethmr** [comment]
The consolidate report that is generated at the end of all the tests can be integrated with Orion-release site like below : 
<img width="615" alt="Screen Shot 2020-08-10 at 7 07 28 PM" src="https://user-images.githubusercontent.com/12869809/89788666-26e12a00-db3d-11ea-84e2-812741e0a367.png">
<img width="1678" alt="Screen Shot 2020-08-10 at 7 08 30 PM" src="https://user-images.githubusercontent.com/12869809/89788688-2c3e7480-db3d-11ea-9107-90744d357a08.png">

**Comment by supreethmr** [comment]
Changes that were discussed on meeting : 
- Considering only performance auditing and report generation for Initial release.
- Comparison of reports will be added later depending on feedback of Initial release.
- Consider using existing web-driver server for performance audit instead of launching new chrome-launcher.
- Explore on option for including performance audit as part `Terra.validates.element()`.
- Limiting the performance audit for default theme when multiple themes are provided.

**Comment by supreethmr** [comment]
I have created new branch to include the changes specified above. 

Link to new Branch : https://github.com/cerner/terra-toolkit-boneyard/compare/lighthouse-integrationII

- New code changes generates lighthouse performance report for given test and stores it under root -> performance_reports folder
- Creates new reports / replaces existing reports for each Test session.
- Runs Performance Test only for default theme when multiple themes are provided.
- Viewports has been classified into Desktop (medium, large, huge, enormous) and Mobile (small, tiny) to reduce the multiple performance test run for same page.
- Total time taken to run WDIO tests has been increased by 2  minutes with integration of lighthouse performance test. ( For Example : for terra-clinical without performance test WDIO would take around 28 minutes in local machine and with performance test it would take around 30 minutes. 
- performance test can be disabled by passing `DISABLE_LIGHT_HOUSE_RUN` flag with WDIO command.
- Creates consolidate report of all the tests at the end of test session.

<img width="1676" alt="Screen Shot 2020-08-19 at 10 45 44 PM" src="https://user-images.githubusercontent.com/12869809/90668443-be492a00-e26d-11ea-8ecd-25fdb873dd0d.png">

- Not able to use existing web-driver server due to incompatibility of  web-driver server's chrome instance with lighthouse module. it throws below error which was caused due to lighthouse not being able to acess chrome port.
```js
Error: Protocol JSON API error (list), status: 404
    at IncomingMessage.response.on (/Users/sm051274/Documents/GitHub/terra-clinical/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:107:18)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by supreethmr** [comment]
Update on pending implementation of functionalities mentioned above. 
> Explore on option for including performance audit as part Terra.validates.element().
- Adding lighthouse Tests to validates element would require changes to exsiting validates element and API might needs to be updated to accept parameters like test-title and test-url etc. 
- Since lighthouse performance test results are not considered for test evaluation like screenshot testing. IMO keeping Lighthouse as service is more precise than adding it to existing validatesElement API.

> Consider using existing web-driver server for performance audit instead of launching new chrome-launcher.
- Existing Web-Dev-Server uses chrome service that runs inside docker for WDIO tests. WDIO tests uses Webdevserver to launch test urls for visual regression tests.
- Lighthouse always launches test page for given url and runs performance audits on them. It requires port address on which chrome instance will be running for performance tests.
- Since selenium_hub runs chrome as service inside container accessing the chrome port `5555` will through 'Error: connect ECONNREFUSED 127.0.0.1:5555 at TCPConnectWrap.afterConnect`. 
- Chrome instance is not accessible like selenium hub from localhost. Could be due to no tcp-port is provided for chrome node like selenium hub.
<img width="1119" alt="Screen Shot 2020-09-01 at 12 57 58 AM" src="https://user-images.githubusercontent.com/12869809/91763941-082dfa80-ebf4-11ea-9f4d-6cbd5cc4f8e4.png">
- Hence Using Chrome-Launcher to launch local chrome instance for lighthouse test.
