### ISSUE TITLE
Wait for browser to become available in the before hook

### ISSUE THREAD

**Issue by StephenEsser** [cerner/terra-toolkit-boneyard#91]
# Feature Request

## Description

As a developer I want to update the Terra service to wait for the browser to become available before running any browser commands.

We'll know we are done when the Terra service before hook waits or validates the browser is available before calling set viewport.

## Additional Context / Screenshots

A few teams are experiencing frequent BROWSER_TIMEOUT errors from the `setViewportSize` command. The before hook of the terra service invokes [setViewport](https://github.com/cerner/terra-toolkit-boneyard/blob/main/src/wdio/services/TerraService.js#L73) which internally uses the [browser.setViewportSize](https://github.com/cerner/terra-toolkit-boneyard/blob/main/src/wdio/services/TerraCommands/viewport-helpers.js#L29) command. If the browser is not available this command will timeout. The service currently pauses for internet explorer:

https://github.com/cerner/terra-toolkit-boneyard/blob/3fdfbebfbeb68ef747c222539eadca3c18e4a5b2/src/wdio/services/TerraService.js#L68-L70

We should update the the service to check/wait for the browser is to become available for all browsers. Ideally we would do some sort of waitFor or polling, but as a last resort we can just do the 10 second pause for all browsers.  

https://github.com/cerner/terra-toolkit-boneyard/blob/3fdfbebfbeb68ef747c222539eadca3c18e4a5b2/src/wdio/services/TerraService.js#L73

Stack trace:

```
Error: A session is either terminated or not started

    at windowHandleSize([object Object]) - setViewportSize.js:83:26

FERROR: Session [e9dfca5689c81e4ebd82c86354115eaf] was terminated due to BROWSER_TIMEOUT

chrome

    at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)

    at Request._callback (/app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)

    at Request.self.callback (/app/node_modules/request/request.js:185:22)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)

    at Object.onceWrapper (events.js:286:20)

    at IncomingMessage.emit (events.js:203:15)

    at IncomingMessage.EventEmitter.emit (domain.js:448:20)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

ERROR: Session [e9dfca5689c81e4ebd82c86354115eaf] was terminated due to BROWSER_TIMEOUT



    at new RuntimeError (/app/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)

    at Request._callback (/app/node_modules/webdriverio/build/lib/utils/RequestHandler.js:318:39)

    at Request.self.callback (/app/node_modules/request/request.js:185:22)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)

    at Request.emit (events.js:198:13)

    at Request.EventEmitter.emit (domain.js:448:20)

    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)

    at Object.onceWrapper (events.js:286:20)

    at IncomingMessage.emit (events.js:203:15)

    at IncomingMessage.EventEmitter.emit (domain.js:448:20)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

Error: A session is either terminated or not started

    at windowHandleSize() - setViewportSize.js:72:17

Error: An unknown server-side error occurred while processing the command.

    at windowHandleSize() - setViewportSize.js:72:17
    ```

**Comment by StephenEsser** [comment]
For reference WebDriverIO v6 project uses waitFor. I am going to propose we do this wait for all browsers instead of only for internet explorer. 

https://github.com/cerner/terra-toolkit/blob/main/packages/terra-functional-testing/src/services/wdio-terra-service.js#L91-L96
